[build]
target = "riscv64gc-unknown-none-elf"
rustflags = ["-Cpanic=abort", "-Clink-arg=-Tsrc/kernel/kernel.ld"]

[target.riscv64gc-unknown-none-elf]
runner = "qemu-system-riscv64 -machine virt -cpu rv64 -smp 1 -m 128M -nographic -bios none -kernel "
